- name: Install Nginx and WordPress
  hosts: wordpress
  become: yes
  gather_facts: true
  vars_files:
    - group_vars/wordpress.yaml
  roles:
    - role: nginx
    - role: mysql
    - role: wordpress

